name: Lint and Test

on: [push, pull_request]

jobs:
  build_and_test:
    runs-on: [ubuntu-latest]
    strategy:
      fail-fast: false

      matrix:
        python-version:
          - "3.8"
          - "3.9"
          - "3.10"
          - "3.11"

    steps:
    - uses: actions/checkout@v2

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install dependencies
      run: |
        python -m pip install -U pip
          pip install -e .
          pip install -e .[dev]

    - name: Python & pip versions
      run: |
        python -V
        pip -V

    - name: Lint
      continue-on-error: true
      run: make lint

    - name: Pylint
      continue-on-error: true
      run: pylint linkrot

    - name: mypy
      continue-on-error: true
      run: mypy linkrot
